<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>303977b6-d1f5-4335-9fe3-db96cbf63f94</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\BuildingBlocks.Contracts\BuildingBlocks.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\Gateway\Gateway.csproj" />
    <ProjectReference Include="..\Services\Catalog\Catalog.Api\Catalog.Api.csproj" />
    <ProjectReference Include="..\Services\Inventory\Inventory.Api\Inventory.Api.csproj" />
    <ProjectReference Include="..\Services\Ordering\Ordering.Api\Ordering.Api.csproj" />
    <ProjectReference Include="..\Functions\Notifications\Notifications.csproj" />
  </ItemGroup>

</Project>
